#ifndef ENGLISH_REPLACEMENTS_H
#define ENGLISH_REPLACEMENTS_H

// Whole word replacements for English
static const std::unordered_map<std::string, std::string> WHOLE_WORD_REPLACEMENTS_ENGLISH = {
    {"approx", "approximately"},
    {"etc", "et cetera"},
    {"e.g", "for example"},
    {"i.e", "that is"},

    //Honorifics
    {"mrs", "misess"},
    {"mr", "mister"},
    {"dr", "doctor"},
    {"st", "saint"},
    {"co", "company"},
    {"jr", "junior"},
    {"maj", "major"},
    {"gen", "general"},
    {"drs", "doctors"},
    {"rev", "reverend"},
    {"lt", "lieutenant"},
    {"hon", "honorable"},
    {"sgt", "sergeant"},
    {"capt", "captain"},
    {"esq", "esquire"},
    {"ltd", "limited"},
    {"col", "colonel"},
    {"ft", "fort"},

    {"bit/s" , "bits per second"},
    {"kbit/s", "kilo bits per second"},
    {"mbit/s", "mega bits per second"},
    {"gbit/s", "giga bits per second"},
    {"tbit/s", "tera bits per second"},
   
    {"b/s" , "bits per second"},
    {"kb/s", "kilo bits per second"},
    {"mb/s", "mega bits per second"},
    {"gb/s", "giga bits per second"},
    {"tb/s", "tera bits per second"},

    {"bps" , "bits per second"},
    {"kbps", "kilo bits per second"},
    {"mbps", "mega bits per second"},
    {"gbps", "giga bits per second"},
    {"tbps", "tera bits per second"},

    //{"am", "A M"},
    {"pm", "p m"},

    {"c++", "c plus plus"},
    {"c#", "c sharp"},

    // File Extensions
    {"txt" , " t x t"},
    {"doc" , " duck"},
    {"docx", " duck x"},
    {"pdf" , " p d f"},
    {"rtf" , " r t f"},
    {"odt" , " o d t"},
    {"ppt" , " p p t"},
    {"pptx", " p p t x"},
    {"xls" , " x l s"},
    {"xlsx", " x l s x"},
    {"csv" , " c s v"},
    {"jpg" , " j p g"},
    {"jpeg", " j peg"},
    {"png" , " p n g"},
    {"bmp" , " b m p"},
    {"svg" , " s v g"},
    {"webp", " web p"},
    {"aac" , " a a c"},
    {"ogg" , " o g g"},
    {"m4a" , " m 4 a"},
    {"mp3" , " m p 3"},
    {"mp4" , " m p 4"},
    {"avi" , " a v i"},
    {"mkv" , " m k v"},
    {"wmv" , " w m v"},
    {"flv" , " f l v"},
    {"webm", " web m"},
    {"7z"  , " seven zip"},
    {"gz"  , " g z"},
    {"msi" , " m s i"},
    {"dll" , " d l l"},
    {"sh"  , " s h"},
    {"apk" , " a p k"},
    {"html", " h t m l"},
    {"htm" , " h t m"},
    {"css" , " c s s"},
    {"js"  , " j s"},
    {"cpp" , " c p p"},
    {"php" , " p h p"},
    {"json", " j son"},
    {"xml" , " x m l"},
    {"sql" , " s q l"},
    {"db"  , " d b"},
    {"mdb" , " m d b"},
    {"sqlite", " s q lite"},
    {"accdb", " a c c d b"},

    {"qwerty", " q verty"},
    
    //Internet
    {"http", "h t t p"},
    {"https", "h t t p s"},
    {"www", "w w w"},
    {"ftp", "f t p"},
};

// Normal replacements for English
static const std::unordered_map<std::string, std::string> NORMAL_REPLACEMENTS_ENGLISH = {
    {"@", "at sign"},
    {"#", "hash"},
    {"%", "percent"},
    {"^", "power"},
    {"&", "and"},
    {"*", "multiply"},
    {"+", "plus"},
    {"/", "slash"},
    {"\\", "backslash"},
    {"=", "equals"},

    {"w/", "with"},
    {"w/o", "without"},
    {"b/c", "because"},
};

#endif